-- Fix missing columns across ShopBot tables (idempotent for PostgreSQL)

-- items
ALTER TABLE items ADD COLUMN IF NOT EXISTS delivery_image VARCHAR;
ALTER TABLE items ADD COLUMN IF NOT EXISTS item_type VARCHAR(8) DEFAULT 'DIGITAL';
ALTER TABLE items ADD COLUMN IF NOT EXISTS category_id INTEGER;
ALTER TABLE items ADD COLUMN IF NOT EXISTS subcategory_id INTEGER;
ALTER TABLE items ADD COLUMN IF NOT EXISTS private_data VARCHAR;
ALTER TABLE items ADD COLUMN IF NOT EXISTS price FLOAT;
ALTER TABLE items ADD COLUMN IF NOT EXISTS is_sold BOOLEAN DEFAULT FALSE;
ALTER TABLE items ADD COLUMN IF NOT EXISTS is_new BOOLEAN DEFAULT TRUE;
ALTER TABLE items ADD COLUMN IF NOT EXISTS description VARCHAR;

-- users
ALTER TABLE users ADD COLUMN IF NOT EXISTS telegram_username VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS telegram_id BIGINT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS top_up_amount FLOAT DEFAULT 0.0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS consume_records FLOAT DEFAULT 0.0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS registered_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS can_receive_messages BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS language VARCHAR(2) DEFAULT 'en';
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_banned BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_code VARCHAR(8);
ALTER TABLE users ADD COLUMN IF NOT EXISTS referred_by_user_id INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS referred_at TIMESTAMP WITH TIME ZONE;

-- categories
ALTER TABLE categories ADD COLUMN IF NOT EXISTS name VARCHAR;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS media_id VARCHAR DEFAULT '';

-- subcategories
ALTER TABLE subcategories ADD COLUMN IF NOT EXISTS name VARCHAR;
ALTER TABLE subcategories ADD COLUMN IF NOT EXISTS media_id VARCHAR DEFAULT '';

-- deposits
ALTER TABLE deposits ADD COLUMN IF NOT EXISTS user_id INTEGER;
ALTER TABLE deposits ADD COLUMN IF NOT EXISTS network VARCHAR(10);
ALTER TABLE deposits ADD COLUMN IF NOT EXISTS amount NUMERIC(78, 0);
ALTER TABLE deposits ADD COLUMN IF NOT EXISTS deposit_datetime TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE deposits ADD COLUMN IF NOT EXISTS fiat_amount FLOAT DEFAULT 0.0;

-- buys
ALTER TABLE buys ADD COLUMN IF NOT EXISTS buyer_id INTEGER;
ALTER TABLE buys ADD COLUMN IF NOT EXISTS total_price FLOAT;
ALTER TABLE buys ADD COLUMN IF NOT EXISTS buy_datetime TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE buys ADD COLUMN IF NOT EXISTS status VARCHAR(9) DEFAULT 'COMPLETED';
ALTER TABLE buys ADD COLUMN IF NOT EXISTS coupon_id INTEGER;
ALTER TABLE buys ADD COLUMN IF NOT EXISTS discount FLOAT DEFAULT 0.0;
ALTER TABLE buys ADD COLUMN IF NOT EXISTS shipping_address VARCHAR;
ALTER TABLE buys ADD COLUMN IF NOT EXISTS track_number VARCHAR;
ALTER TABLE buys ADD COLUMN IF NOT EXISTS shipping_option_id INTEGER;

-- cart_items
ALTER TABLE cart_items ADD COLUMN IF NOT EXISTS cart_id INTEGER;
ALTER TABLE cart_items ADD COLUMN IF NOT EXISTS item_type VARCHAR(8) DEFAULT 'DIGITAL';
ALTER TABLE cart_items ADD COLUMN IF NOT EXISTS category_id INTEGER;
ALTER TABLE cart_items ADD COLUMN IF NOT EXISTS subcategory_id INTEGER;
ALTER TABLE cart_items ADD COLUMN IF NOT EXISTS quantity INTEGER;

-- coupons
ALTER TABLE coupons ADD COLUMN IF NOT EXISTS name VARCHAR;
ALTER TABLE coupons ADD COLUMN IF NOT EXISTS code VARCHAR(12);
ALTER TABLE coupons ADD COLUMN IF NOT EXISTS type VARCHAR(10);
ALTER TABLE coupons ADD COLUMN IF NOT EXISTS value NUMERIC(10, 2);
ALTER TABLE coupons ADD COLUMN IF NOT EXISTS create_datetime TIMESTAMP WITH TIME ZONE;
ALTER TABLE coupons ADD COLUMN IF NOT EXISTS expire_datetime TIMESTAMP WITH TIME ZONE;
ALTER TABLE coupons ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE coupons ADD COLUMN IF NOT EXISTS usage_limit INTEGER DEFAULT 1;
ALTER TABLE coupons ADD COLUMN IF NOT EXISTS usage_count INTEGER DEFAULT 0;

-- shipping_options
ALTER TABLE shipping_options ADD COLUMN IF NOT EXISTS name VARCHAR;
ALTER TABLE shipping_options ADD COLUMN IF NOT EXISTS price FLOAT;
ALTER TABLE shipping_options ADD COLUMN IF NOT EXISTS is_disabled BOOLEAN DEFAULT FALSE;

-- payments
ALTER TABLE payments ADD COLUMN IF NOT EXISTS user_id INTEGER;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS processing_payment_id INTEGER;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS message_id INTEGER;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS is_paid BOOLEAN DEFAULT FALSE;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS expire_datetime TIMESTAMP WITH TIME ZONE;

-- buttons_media
ALTER TABLE buttons_media ADD COLUMN IF NOT EXISTS media_id VARCHAR;
ALTER TABLE buttons_media ADD COLUMN IF NOT EXISTS button VARCHAR(14);

-- reviews
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS buyItem_id INTEGER;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS text VARCHAR;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS image_id VARCHAR;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS rating SMALLINT;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS create_datetime TIMESTAMP WITH TIME ZONE;

-- referral_bonus
ALTER TABLE referral_bonus ADD COLUMN IF NOT EXISTS referral_user_id INTEGER;
ALTER TABLE referral_bonus ADD COLUMN IF NOT EXISTS referrer_user_id INTEGER;
ALTER TABLE referral_bonus ADD COLUMN IF NOT EXISTS payment_amount FLOAT;
ALTER TABLE referral_bonus ADD COLUMN IF NOT EXISTS applied_referral_bonus FLOAT;
ALTER TABLE referral_bonus ADD COLUMN IF NOT EXISTS applied_referrer_bonus FLOAT;
